---

- name: Set repo clone destination path
  set_fact:
    git_clone_path: "{{ ansible_facts.user_dir }}\\Documents\\GitHub\\terraform-azurerm-resourcegroup"

- name: Create git repo path
  ansible.windows.win_file:
    path: "{{ git_clone_path }}"
    state: directory

- name: Clone git repo
  ansible.windows.win_command: "git clone https://github.com/tonyskidmore/terraform-azurerm-resourcegroup.git {{ git_clone_path }}"
  args:
    creates: "{{ git_clone_path }}\\.git"

- name: Set git config
  ansible.windows.win_command: "{{ item }}"
  register: git_config
  loop:
    - 'git config --global user.email "16082810+tonyskidmore@users.noreply.github.com"'
    - 'git config --global user.name "Tony Skidmore"'

- name: Debug git config
  debug:
    var: git_config
    verbosity: "{{ verbosity_level }}"
