---

- name: Create git repo path
  vars:
    git_clone_path: "{{ ansible_facts.user_dir }}\\Documents\\GitHub\\{{ item.name }}"
  ansible.windows.win_file:
    path: "{{ git_clone_path }}"
    state: directory
  loop: "{{ git_clone_repos }}"
  when:
    - git_clone_repos is defined
    - git_clone_repos | length

- name: Clone git repo
  vars:
    git_clone_path: "{{ ansible_facts.user_dir }}\\Documents\\GitHub\\{{ item.name }}"
  ansible.windows.win_command: "git clone {{ item.url }} {{ git_clone_path }}"
  args:
    creates: "{{ git_clone_path }}\\.git"
  loop: "{{ git_clone_repos }}"
  when:
    - git_clone_repos is defined
    - git_clone_repos | length

- name: Set git config
  ansible.windows.win_command: "{{ item }}"
  register: git_config
  loop: "{{ git_config }}"
  when:
    - git_config is defined
    - git_config | length

- name: Debug git config
  debug:
    var: git_config
    verbosity: "{{ verbosity_level }}"
