---

  # will always need git and will trigger Chocolatey install
- name: Install git
  win_chocolatey:
    name: git
    state: present
  register: git_install

- name: debug git_install
  debug:
    var: git_install

- name: Install terraform
  win_chocolatey:
    name: terraform
    state: present
