---

  # will always need git and will trigger Chocolatey install
- name: Install git
  win_chocolatey:
    name: git
    state: present
  register: git_install

- name: debug git_install
  debug:
    var: git_install

- name: Reboot after first chocolatey install
  win_reboot:
  when:
    - git_install.warnings is defined
    - git_install.warnings is search("was installed during this task")

- name: Install terraform packages
  win_chocolatey:
    name: "{{ terraform_packages }}"
    state: present
  # loop: "{{ terraform_packages }}"
  when:
    - terraform_packages | length

# - name: Install azure packages
#   win_chocolatey: azure_packages
#     name: "{{ item }}"
#     state: present
#   loop: "{{ azure_packages }}"
#   when:
#     - azure_packages | length

# - name: Install windows packages
#   win_chocolatey: windows_packages
#     name: "{{ item }}"
#     state: present
#   loop: "{{ windows_packages }}"
#   when:
#     - windows_packages | length
