---

- name: Get user context
  win_whoami:
  register: win_whoami

- name: Debug win_whoami
  debug:
    var: win_whoami

- name: Install windows packages
  win_chocolatey:
    name: "{{ item }}"
    state: present
  loop: "{{ windows_packages }}"
  when:
    - install_windows_packages
    - windows_packages | length

- name: Install Windows Subsystem for Linux (WSL)
  include_tasks:
    file: wsl.yml
  when:
    - install_wsl

  # will always need git and will trigger Chocolatey install
- name: Install git
  win_chocolatey:
    name: git
    state: present
  register: git_install

- name: debug git_install
  debug:
    var: git_install

- name: Reboot after first chocolatey install
  win_reboot:
  when:
    - git_install.warnings is defined
    - git_install.warnings is search("was installed during this task")

# feed in a list
- name: Install terraform packages
  win_chocolatey:
    name: "{{ terraform_packages }}"
    state: present
  when:
    - terraform_packages | length

# or loop a list
- name: Install azure packages
  win_chocolatey:
    name: "{{ item }}"
    state: present
  loop: "{{ azure_packages }}"
  when:
    - azure_packages | length



- name: Install Python packages
  win_chocolatey:
    name: "{{ item }}"
    state: present
  register: python_result
  loop: "{{ python_packages }}"
  when:
    - python_packages | length

  # TODO: is this needed?
- name: Reboot after python install for system path
  win_reboot:
  when: python_result is changed

- name: PowerShell module packages
  win_chocolatey:
    name: "{{ item }}"
    state: present
  loop: "{{ powershell_packages }}"
  when:
    - powershell_packages | length

- name: Visual Studio Code packages
  win_chocolatey:
    name: "{{ item }}"
    state: present
  loop: "{{ vscode_packages }}"
  when:
    - vscode_packages | length

- name: Install pre-commit
  include_tasks:
    file: pre-commit.yml
  when:
    - install_pre_commit

- name: Clone got repos
  include_tasks:
    file: git_repos.yml

- name: Configure Windows Subsystem for Linux (WSL)
  include_tasks:
    file: wsl_config.yml
  when:
    - configure_wsl
