---

# - name: Update Python package manager components
#   pip:
#     name: "{{ item }}"
#     state: latest
#   loop:
#     - pip
#     - setuptools

- name: Update Python pip
  win_command: "python -m pip install --upgrade pip"

- name: Update Python setuptools
  win_command: "python -m pip install --upgrade setuptools"

# - name: Install pipx
#   pip:
#     name: pipx
#     state: present
#   register: pip_pipx
#   environment:
#     PIPX_BIN_DIR = "${env:ProgramFiles(x86)}\pipx_bin"
#     PIPX_HOME = "${env:ProgramFiles(x86)}\pipx"

- name: Get pipx version
  win_command: "pipx --version"
  change_when: no
  ignore_errors: yes
  register: pipx_version

- name: Debug pipx_version
  debug:
    var: pipx_version

- name: Install pipx package
  win_command: set
  # win_command: "python -m pip install pipx"
  # args:
  #   creates: 'C:\Python310\Scripts\pipx.exe'
  register: pip_pipx
  environment:
    PIPX_BIN_DIR: 'C:\Program Files (x86)\pipx_bin'
    PIPX_HOME: 'C:\Program Files (x86)\pipx'
  when:
    - pipx_version is failed

- name: Debug pip_pipx
  debug:
    var: pip_pipx

  # Add to system path
- name: Pipx ensure path
  win_path:
    elements:
      - 'C:\Program Files (x86)\pipx_bin'
  when:
    - pipx_version is failed

- name: Reboot after pipx install for system path
  win_reboot:
  when: pip_pipx is changed

- name: Pipx install pre-commit
  win_command: "pipx install pre-commit"
  register: pipx_pre_commit
  when: pip_pipx is changed

- name: Debug pipx_pre_commit
  debug:
    var: pipx_pre_commit 
