---

# - name: Update Python package manager components
#   pip:
#     name: "{{ item }}"
#     state: latest
#   loop:
#     - pip
#     - setuptools

- name: Update Python pip
  win_command: "python -m pip install --upgrade pip"


- name: Update Python setuptools
  win_command: "python -m pip install --upgrade setuptools"

# - name: Install pipx
#   pip:
#     name: pipx
#     state: present
#   register: pip_pipx
#   environment:
#     PIPX_BIN_DIR = "${env:ProgramFiles(x86)}\pipx_bin"
#     PIPX_HOME = "${env:ProgramFiles(x86)}\pipx"

- name: Update Python package manager components
  win_command: "python -m pip install pipx"
  register: pip_pipx
  environment:
    PIPX_BIN_DIR = "${env:ProgramFiles(x86)}\pipx_bin"
    PIPX_HOME = "${env:ProgramFiles(x86)}\pipx"

- name: Debug pip_pipx
  debug:
    var: pip_pipx

  # Add to system path
- name: Pipx ensure path
  win_path:
    elements:
      - "C:\Program Files (x86)}\pipx_bin"

- name: Pipx install pre-commit
  win_command: "pipx install pre-commit"
  register: pipx_pre_commit

- name: Debug pipx_pre_commit
  debug:
    var: pipx_pre_commit 
