---

- name: Update Python package manager components
  pip:
    name: "{{ item }}"
    state: latest
  loop:
    - pip
    - setuptools

- name: Install pipx
  pip:
    name: pipx
    state: present
  register: pip_pipx
  environment:
    PIPX_BIN_DIR = "${env:ProgramFiles(x86)}\pipx_bin"
    PIPX_HOME = "${env:ProgramFiles(x86)}\pipx"

- name: Debug pip_pipx
  debug:
    var: pip_pipx

- name: Pipx ensure path
  win_command: "pipx ensurepath"
  register: pipx_ensurepath

- name: Debug pipx_ensurepath
  debug:
    var: pipx_ensurepath

- name: Pipx install pre-commit
  win_command: "pipx install pre-commit"
  register: pipx_pre_commit

- name: Debug pipx_pre_commit
  debug:
    var: pipx_pre_commit 
