---

# - name: Update Python package manager components
#   pip:
#     name: "{{ item }}"
#     state: latest
#   loop:
#     - pip
#     - setuptools

- name: Update Python pip
  win_command: "python -m pip install --upgrade pip"

- name: Update Python setuptools
  win_command: "python -m pip install --upgrade setuptools"

# - name: Install pipx
#   pip:
#     name: pipx
#     state: present
#   register: pip_pipx
#   environment:
#     PIPX_BIN_DIR = "${env:ProgramFiles(x86)}\pipx_bin"
#     PIPX_HOME = "${env:ProgramFiles(x86)}\pipx"

- name: Get pipx version
  win_command: "pipx --version"
  changed_when: no
  ignore_errors: yes
  register: pipx_version

- name: Debug pipx_version
  debug:
    var: pipx_version

- name: Set pipx envronment
  ansible.windows.win_environment:
    level: machine
    variables:
      PIPX_BIN_DIR: 'C:\Program Files (x86)\pipx_bin'
      PIPX_HOME: 'C:\Program Files (x86)\pipx'    
  register: set_pipex_vars

  # Add to system path
- name: Pipx ensure path
  win_path:
    elements:
      - 'C:\Program Files (x86)\pipx_bin'
  when:
    - pipx_version is failed

- name: Debug set_pipex_vars
  debug:
    var: set_pipex_vars

- name: Reboot after pipx install for system path
  win_reboot:
  when: set_pipex_vars is changed

- name: Gather facts
  setup:
  register: win_setup

- name: Debug win_setup
  debug:
    var: win_setup

- name: Install pipx package
  win_command: "python -m pip install pipx"
  args:
    creates: 'C:\Python310\Scripts\pipx.exe'
  register: pip_pipx
  # environment:
  #   PIPX_BIN_DIR: 'C:\Program Files (x86)\pipx_bin'
  #   PIPX_HOME: 'C:\Program Files (x86)\pipx'
  when:
    - pipx_version is failed

- name: Debug pip_pipx
  debug:
    var: pip_pipx

- name: Get pre-commit version
  win_command: "pre-commit --version"
  changed_when: no
  ignore_errors: yes
  register: precommit_version

- name: Pipx install pre-commit
  win_command: "pipx install pre-commit"
  register: pipx_pre_commit
  when:
    - precommit_version is failed

- name: Debug pipx_pre_commit
  debug:
    var: pipx_pre_commit 
