---

- name: Visual Studio Code packages
  win_chocolatey:
    name: "{{ item }}"
    state: present
  loop: "{{ vscode_packages }}"

- name: Get Visual Studio Code extensions
  ansible.windows.win_shell: "code.cmd --list-extensions"
  changed_when: no
  register: vscode_installed_extensions
  when:
    - vscode_extensions | length

- debug: var=vscode_installed_extensions

- name: Install Visual Studio Code extensions
  ansible.windows.win_shell: "code.cmd --install-extension {{ item }}"
  loop: "{{ vscode_extensions }}"
  when:
    - vscode_packages | length
    - vscode_extensions | length
