---

# https://github.com/microsoft/terminal/archive/refs/tags/v1.11.3471.0.zip

- name: Install using msix method
  tags:
    - windows_terminal
  block:

    - name: Create temporary download directory
      ansible.windows.win_tempfile:
        state: directory
        suffix: msix
      register: msix_download_dir
      tags:
        - windows_terminal

    - name: Debug msix_download_dir
      debug:
        var: msix_download_dir
        verbosity: "{{ verbosity_level }}"

    - name: Download msix .zip package
      ansible.windows.win_get_url:
        url: https://github.com/microsoft/terminal/releases/download/v1.11.3471.0/Microsoft.WindowsTerminal_1.11.3471.0_8wekyb3d8bbwe.msixbundle
        dest: "{{ msix_download_dir.path }}\\win_term.msixbundle"

    # - name: Unzip msix file
    #   community.windows.win_unzip:
    #     src: "{{ msix_download_dir.path }}\\win_term.zip"
    #     dest: "{{ msix_download_dir.path }}\\win_term_dir"
    #     creates: "{{ msix_download_dir.path }}\\win_term_dir"
    #   register: msix_unzip

    # - name: Debug msix_unzip
    #   debug:
    #     var: msix_unzip
    #     verbosity: "{{ verbosity_level }}"

    - name: Install Windows Terminal msixbundle
      ansible.windows.win_package:
        path: "{{ msix_download_dir.path }}\\win_term.msixbundle"
        provider: msix
        state: present
      register: win_term_msix_install
      become: yes
      become_method: runas
      become_flags: logon_type=interactive logon_flags=with_profile
      vars:
        ansible_become_user: "{{ ansible_user }}"
        ansible_become_password: "{{ ansible_password }}"

    - name: Debug win_term_msix_install
      debug:
        var: win_term_msix_install
        verbosity: "{{ verbosity_level }}"
