---

- name: Debug ansible_facts
  debug:
    var: ansible_facts

- name: Install Windows Subsystem for Linux (wsl2)
  win_command: wsl --status
  register: wsl_status
  ignore_errors: yes

- name: Debug WSL install status
  debug:
    var: wsl_status

- debug:
    msg: "{{ wsl_status.stdout | to_yaml }}"

- name: Install Windows Subsystem for Linux (wsl2)
  win_command: wsl --install
  register: wsl_install
  when:
    - wsl_status is failed

- name: Debug WSL install status
  debug:
    var: wsl_install

- name: Configure WSL
  block:

    - name: Create user
      win_command: powershell.exe -
      args:
        stdin: Start-Process "ubuntu.exe" -NoNewWindow -ArgumentList "useradd -m tony"

  when:
    - configure_wsl