---

- name: Debug ansible_facts
  debug:
    var: ansible_facts

- name: Install Windows Subsystem for Linux (wsl2)
  win_command: wsl --status
  register: wsl_status
  ignore_errors: yes
  changed_when: no

- name: Debug WSL install status
  debug:
    var: wsl_status

- debug:
    msg: "{{ wsl_status.stdout | to_yaml }}"

- name: Install Windows Subsystem for Linux (wsl2)
  win_command: wsl --install
  register: wsl_install
  when:
    - wsl_status is failed

- name: Debug WSL install status
  debug:
    var: wsl_install

- name: Configure WSL
  block:

    - name: Create user
      ansible.windows.win_powershell:
      script: |
        Start-Process "ubuntu.exe" -NoNewWindow -ArgumentList "useradd -m tony"
      register: wsl_config_script

    - debug:
        var: wsl_config_script

  when:
    - configure_wsl