---

- name: Debug ansible_facts
  debug:
    var: ansible_facts

- name: Install Windows Subsystem for Linux (wsl2)
  win_command: wsl --install
  register: wsl_install

- name: Debug WSL install status
  debug:
    var: wsl_install.failed

- name: Configure WSL
  block:

    - name: Create user
      win_powershell:
        script: |
          Start-Process "ubuntu.exe" -NoNewWindow -ArgumentList "useradd -m tony"

  when:
    - configure_wsl