---


# https://askubuntu.com/questions/1248825/how-can-i-fix-internet-connection-issues-on-wsl2
- name: Copy .wslconfig to remote profile path
  ansible.windows.win_copy:
    src: "files/.wslconfig"
    dest: "{{ win_user_profile_path }}/.wslconfig"

- name: Turn off IPv6 on all adapters
  ansible.windows.win_powershell:
    script: |
      Get-NetAdapter | Select-Object Name, InterfaceDescription
      Disable-NetAdapterBinding -Name "*" -ComponentID ms_tcpip6
      Get-NetAdapterBinding | Where-Object ComponentID -eq ms_tcpip6
  register: disable_ipv6

- name: Debug disable_ipv6
  debug:
    var: disable_ipv6
    verbosity: "{{ verbosity_level }}"

- name: Create ansible directory
  ansible.windows.win_file:
    path: "{{ ansible_remote_path }}"
    state: directory

- name: Copy scripts to ansible remote path
  ansible.windows.win_copy:
    src: "files/{{ item.script }}"
    dest: "{{ ansible_remote_path }}\\{{ item.script }}"
  loop: "{{ configure_wsl_scripts }}"

- name: Configure default WSL user
  ansible.windows.win_powershell:
    script: |
      wsl -d ubuntu -u root bash -ic "useradd -m {{ ansible_user }}"
      wsl -d ubuntu -u root bash -ic "passwd -d {{ ansible_user }}"
      wsl -d ubuntu -u root bash -ic "echo '%{{ ansible_user }} ALL=(ALL:ALL) NOPASSWD:ALL' > /etc/sudoers.d/{{ ansible_user }}"
      wsl -d ubuntu -u root bash -ic "echo '[user]' > /etc/wsl.conf"
      wsl -d ubuntu -u root bash -ic "echo 'default={{ ansible_user }}' >> /etc/wsl.conf"
      wsl -d ubuntu -u root bash -ic "echo '[interop]' >> /etc/wsl.conf"
      wsl -d ubuntu -u root bash -ic "echo 'enabled = false' >> /etc/wsl.conf"
      wsl -d ubuntu -u root bash -ic "echo 'appendWindowsPath = false' >> /etc/wsl.conf"
      # wsl -d ubuntu -u root bash -ic "echo '[network]' >> /etc/wsl.conf"
      # wsl -d ubuntu -u root bash -ic "echo 'generateResolvConf = false' >> /etc/wsl.conf"
      # wsl -d ubuntu -u root bash -ic "unlink /etc/resolv.conf"
      # wsl -d ubuntu -u root bash -ic "echo 'nameserver 1.1.1.1' > /etc/resolv.conf"
      # wsl -d ubuntu -u root bash -ic "echo 'nameserver 8.8.8.8' >> /etc/resolv.conf"
  register: wsl_default_user

- name: Debug wsl_default_user
  debug:
    var: wsl_default_user
    verbosity: "{{ verbosity_level }}"

- name: Create ansible directory in ansible remote path
  ansible.windows.win_file:
    path: "{{ ansible_remote_path }}"
    state: directory

- name: Set local SSH key path fact
  set_fact:
    ssh_key_path: "{{ playbook_dir }}/win_files/id_rsa"

- name: Check for SSH private key
  ansible.builtin.stat:
    path: "{{ ssh_key_path }}"
  register: ssh_key_stat
  delegate_to: localhost

- name: Debug ssh_key_stat
  debug:
    var: ssh_key_stat
    verbosity: "{{ verbosity_level }}"

- name: Create SSH key private key file
  block:

    - name: Get decoded SSH private key content
      set_fact:
        ssh_private_key_content: "{{ lookup('file', ssh_key_path) | b64decode }}"

    - name: Copy SSH key to ansible remote path
      ansible.windows.win_copy:
        content: "{{ ssh_private_key_content }}"
        dest: "{{ ansible_remote_path }}\\id_rsa"

    - name: Copy other ansible content files
      ansible.windows.win_copy:
        src: "{{ playbook_dir }}/win_files/{{ item }}"
        dest: "{{ ansible_remote_path }}\\"
      loop:
        - inventory
        - ansible.cfg
        - linux.yml
        - requirements.yml

  when:
    - ssh_key_stat.stat.exists

- name: Experimenting with MTU size due to WSL -> debian based SSH communication issues
  block:

    # netsh interface ipv4 show subinterface
    # netsh interface ipv4 set subinterface "vEthernet (WSL)" mtu=1350 store=persistent
    - name: Check MTU of 'vEthernet (WSL)' interface
      win_shell: "(Get-NetIPInterface -InterfaceAlias 'vEthernet (WSL)').NlMtu"
      changed_when: False
      register: wsl_mtu

    - name: debug wsl_mtu
      debug:
        var: wsl_mtu
        verbosity: "{{ verbosity_level }}"

    - name: Change MTU of 'vEthernet (WSL)' interface
      win_shell: "Set-NetIPInterface -InterfaceAlias 'vEthernet (WSL)' -NlMtuBytes {{ wsl_mtu_size }} -AddressFamily 'IPv4'"
      changed_when: wsl_mtu.stdout|trim != wsl_mtu_size

  when:
    - configure_wsl_mtu

- name: Include WSL config scripts
  include_tasks:
    file: wsl_scripts.yml
  loop: "{{ configure_wsl_scripts }}"
  loop_control:
    loop_var: wsl_script_item
  when:
    - configure_wsl_scripts is defined
    - configure_wsl_scripts | length

- name: Create WSL application shortcut on the desktop
  community.windows.win_shortcut:
    src: C:\\Windows\\System32\\bash.exe
    dest: C:\Users\Public\Desktop\WSL.lnk
    icon: C:\Windows\System32\wsl.exe,0
    directory: "\\\\wsl$\\ubuntu\\home\\{{ ansible_user }}"
