---

- name: Create user
  ansible.windows.win_powershell:
    script: |
      Start-Process "ubuntu.exe" -NoNewWindow -ArgumentList "useradd -m adminuser"
  register: wsl_config_script

# - name: Set default user
#   win_command: 

- debug:
    var: wsl_config_script

