---

- name: Update Ubuntu WSL
  ansible.windows.win_powershell:
    script: |
      wsl -d ubuntu -u root bash -ic "apt update; apt upgrade -y"
  register: wsl_update

- name: Configure default WSL user
  ansible.windows.win_powershell:
    script: |
      wsl -d ubuntu -u root bash -ic "useradd -m adminuser"
      wsl -d ubuntu -u root bash -ic "passwd -d adminuser"
      wsl -d ubuntu -u root bash -ic "echo '%adminuser ALL=(ALL:ALL) NOPASSWD:ALL' > /etc/sudoers.d/adminuser"
      wsl -d ubuntu -u root bash -ic "echo '[user]\ndefault=adminuser' > /etc/wsl.conf"
  register: wsl_default_user

- name: Terminate WSL
  ansible.windows.win_powershell:
    script: |
      wsl -t ubuntu
  register: wsl_terminate

- debug:
    var: "{{ item }}"
    verbosity: "{{ verbosity_level }}"
  loop:
    - 'wsl_update'
    - 'wsl_default_user'
    - 'wsl_terminate'
