---

- name: "Run WSL script - {{ wsl_script_item.script }}"
  ansible.windows.win_powershell:
    script: |
      wsl -d ubuntu -u {{ wsl_script_item.user }} bash -ic "/mnt/c/ProgramData/ansible/{{ wsl_script_item.script }}"
  register: wsl_script_install_result

- name: Debug wsl_script_install_result
  debug:
    var: wsl_script_install_result
    verbosity: "{{ verbosity_level }}"

- name: Terminate WSL
  ansible.windows.win_powershell:
    script: |
      wsl -t ubuntu
  register: wsl_terminate
  when:
    - wsl_script_item.terminate_post_script

# https://github.com/MicrosoftDocs/WSL/blob/main/WSL/wsl-config.md#the-8-second-rule
- name: Wait for WSL termination
  pause:
    seconds: 10
  when:
    - wsl_script_item.terminate_post_script
